spring.datasource.url=jdbc:postgresql://localhost:5432/core_bank_system
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASSWORD}
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.clean-disabled=true
spring.flyway.baseline-on-migrate=false

application.security.jwt.secret-key=${PROD_JWT_SECRET_KEY}
application.security.encryption-key=${PROD_ENCRYPTION_KEY}

