spring.application.name=core_bank_system
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.clean-disabled=true
spring.flyway.locations=classpath:db/migration

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=900000
application.security.jwt.refresh-token.expiration=604800000
application.security.encryption-key=${ENCRYPTION_KEY:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}

